version: '3.8'

services:

  server:
    build: .
    ports:
      - '6006:7001'
    image: gcr.io/glowing-reserve-336013/bird-box
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M
    healthcheck:
      test: socat - TCP4:localhost:7001 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
