version: '3.8'

services:

  plasticine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    image: gcr.io/glowing-reserve-336013/plasticine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl --fail http://localhost:8000/encryptedFlag || exit 1
      interval: 60s
      timeout: 2s
      retries: 5