version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: passparser-server
    image: gcr.io/glowing-reserve-336013/passparser
    ports:
      - 8000:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl --fail http://localhost:80 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5

